#Tic Tac Toe by Poh Boon Siong
#Description:
#2-Player Tic Tac Toe

import random

def main():
    #Call Display_Help() function
    Display_Help()
    #Display & Save Picked Player
    Player_Picked = Player_Picker()
    print('\t\t==='+ Player_Picked + ' START FIRST===\t\t\n')
    print('============================================================')
    #Call the Tic_Tac_Toe() function
    board()
    Tic_Tac_Toe(Player_Picked)

def Display_Help():
    print('============================================================')
    print('\t\t    2-Player Tic Tac Toe    \t\t')
    print('============================================================')
    print('\t\t     ===HOW TO PLAY===  \t\t\n')
    print('1. Player 1 will be NOUGHTS(O)\n')
    print('2. Player 2 will be CROSSES(X)\n')
    print('3. A 3 by 3 grid will be generated by the program\n')
    print('4. The program will randomly pick a player to start\n')
    print('5. Upon being prompted for the your choice,\n   please key in this EXACT format: row, column (e.g. A, 1)\n')
    print('\t\t===PRESS ENTER TO START===\t\t')
    print('============================================================')
    input()

def Player_Picker():
    #By random choice
    #Using Python's 'random' Library
    #List for the program to pick
    Player_List = ['Player 1', 'Player 2']
    Picked_Player = random.choice(Player_List)
    return Picked_Player


def Tic_Tac_Toe(Player_Picked):
    #Display Player Turn
    print("Turn: " + Player_Picked)
    if Player_Picked == 'Player 1':
        respective_input = 'O'
        Next_Player = 'Player 2'
    elif Player_Picked == 'Player 2':
        respective_input = 'X'
        Next_Player = 'Player 1'
    

    player_choice = input(Player_Picked + ' Please enter your choice (Row, Column): ')
    #Remove whitespaces, and split into 2 items and put into list
    choice_list = player_choice.replace(' ', '').split(',')
    row = choice_list[0]
    column = int(choice_list[1])
    #Check the row and column, and input the respective input
    if row == 'a' or row == 'A':
        A[column - 1] = respective_input
    elif row == 'b' or row == 'B':
        B[column - 1] = respective_input
    elif row == 'c' or row == 'C':
        C[column - 1] = respective_input

    print("   1  2  3 ")
    print("A  " + A[0] + '  ' + A[1] + '  ' + A[2] + ' ')
    print("B  " + B[0] + '  ' + B[1] + '  ' + B[2] + ' ')
    print("C  " + C[0] + '  ' + C[1] + '  ' + C[2] + ' ')
    # Check for win
    if A[0] == 'O' and A[1] == 'o' and A[2] == 'O'

def board():
    #Locking System that does not allow player to override the existing tile (anti cheat)
    #Display Board
    A = ['', '', '']
    B = ['', '', '']
    C = ['', '', '\n']

    print("   1  2  3 ")
    print("A  " + A[0] + '  ' + A[1] + '  ' + A[2] + ' ')
    print("B  " + B[0] + '  ' + B[1] + '  ' + B[2] + ' ')
    print("C  " + C[0] + '  ' + C[1] + '  ' + C[2] + ' ')

if __name__=='__main__':
    main()    